micronaut:
  application:
    name: demo
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}